### ISSUE TITLE
Question About config.py

### ISSUE THREAD

**Issue by china1885** [Hzzone/Precipitation-Nowcasting#14]
What are the paths '**HKO_PNG_PATH**' and '**HKO_MASK_PATH**' in config.py used for?  
Are they temporary directories and supposed to be empty before running , or supposed to be filled with some input png pictures(if so, how can I get those pictures)?
`for dirs in ['/Users/hzzone/Downloads/HKO-7_data/radarPNG', '/home/hzzone/HKO-7/radarPNG']:
if os.path.exists(dirs):
        __C.HKO_PNG_PATH = dirs`

When I run `python 'experiments/trajGRU_balanced_mse_mae/main.py'` with those directories empty, **IOError** occured, details were as follow:
`Traceback (most recent call last):
  File "experiments/trajGRU_balanced_mse_mae/main.py", line 49, in <module>
    train_and_test(encoder_forecaster, optimizer, criterion, mult_step_scheduler, batch_size, max_iterations, test_iteration_interval, test_and_save_checkpoint_iterations, folder_name)
  File "C:\Users\Dennis\Desktop\2020.10.26 radar\Precipitation-Nowcasting-master\nowcasting\train_and_test.py", line 53, in train_and_test
    train_hko_iter.sample(batch_size=batch_size)
  File "C:\Users\Dennis\Desktop\2020.10.26 radar\Precipitation-Nowcasting-master\nowcasting\hko\dataloader.py", line 453, in sample
    frame_dat, mask_dat = self._load_frames(datetime_clips=datetime_clips)
  File "C:\Users\Dennis\Desktop\2020.10.26 radar\Precipitation-Nowcasting-master\nowcasting\hko\dataloader.py", line 324, in _load_frames
    grayscale=True)
  File "C:\Users\Dennis\Desktop\2020.10.26 radar\Precipitation-Nowcasting-master\nowcasting\hko\image.py", line 115, in quick_read_frames
    raise IOError
OSError`

**Comment by kxgy2018** [comment]
In my view, these paths are used to store radar pictures. Are you learning this project? If so, I want to have more communication with you. My e-mail address is 1290477691@qq.com.

**Comment by zzwei1** [comment]
> In my view, these paths are used to store radar pictures. Are you learning this project? If so, I want to have more communication with you. My e-mail address is [1290477691@qq.com](mailto:1290477691@qq.com).

I'm studying radar echo extrapolation too, may be we can communicate more.

**Comment by kxgy2018** [comment]
> > In my view, these paths are used to store radar pictures. Are you learning this project? If so, I want to have more communication with you. My e-mail address is [1290477691@qq.com](mailto:1290477691@qq.com).
> 
> I'm studying radar echo extrapolation too, may be we can communicate more.

I think so. You can contact me at the email address above.

**Comment by ylsgbjc** [comment]
How did you solve the IOError problem?

**Comment by S-haaaaa** [comment]
> > > In my view, these paths are used to store radar pictures. Are you learning this project? If so, I want to have more communication with you. My e-mail address is [1290477691@qq.com](mailto:1290477691@qq.com).
> > 
> > 
> > I'm studying radar echo extrapolation too, may be we can communicate more.
> 
> I think so. You can contact me at the email address above.

Hello! Can I ask you about a problem I'm having reproducing this paper?

**Comment by jichongxing2023** [comment]
I know how run it. My e-mail address is [954405918@qq.com](mailto:954405918@qq.com).
